name: Juicy pineapple juice
on: 
  workflow_dispatch: 
jobs:
  producer:
    name: Special producer
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Run bash
        id: run_bash
        run: |
          ls
